---
name: build-and-push

on:
  push:
    branches: ['**']

jobs:
  docker-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: docker/metadata-action@v5.7.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6.18.0
        with:
          context: ./project
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
